name: Benchmark

on:
  issue_comment:
    types: [created]

jobs:
  benchmark_main:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/run-benchmark')
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Create virtual environment
        run: python -m venv bitblas_benchmark
      
      - name: Activate virtual environment and install dependencies
        run: |
          source bitblas_benchmark/bin/activate
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi

      - name: Install project in wheel mode
        run: |
          source bitblas_benchmark/bin/activate
          python -m pip install .
        
      - name: Matmul Benchmark
        source bitblas_benchmark/bin/activate
        cd benchmark/operators
        python ./benchmark_ops_matmul.py
