name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        python -m pip install wheel setuptools

    - name: Run format
      run: ./format.sh

    - name: Install project in editable mode
      run: |
        pip install -e .
    
    # - name: Run cpp tests
    #   run: |
    #     cd testing/cpp
    #     mkdir build
    #     cd build
    #     cmake ..
    #     make -j
